---
title: "lasso_regresyon"
author: "lasso_regresyon"
date: "18 09 2021"
output: html_document
---

#Model

```{r}

train_x_x<-train_x %>% 
  dplyr::select(-c("League","NewLeague","Division"))  # kategorik degiskenleri cikarttik

lasso_fit<-glmnet(as.matrix(train_x_x),
                  y=train_y,
                  alpha=1
                  )# alpha 1 lasso icin alpha 0 ridge icin
lasso_fit

summary(lasso_fit)

names(lasso_fit) # icinden erisilebilecek degerler

lasso_fit$beta

plot(lasso_fit,xvar="lambda",label=T)

tidy(lasso_fit)

lasso_fit$beta # bazilarini sıfırlamis

```

#Dogru lambda icin cv'nin kullanilmasi

```{r}
lasso_cv_fit<-cv.glmnet(as.matrix(train_x_x),
                  y=train_y,
                  alpha=1
                  )

lasso_cv_fit$lambda
lasso_cv_fit
plot(lasso_cv_fit)

lasso_cv_fit$lambda.min
lasso_cv_fit$lambda.1se

coef(lasso_cv_fit,"lambda.min") # katsayilari optimize eder

tidy(lasso_cv_fit)
glance(lasso_cv_fit)  # min,1se degerleri verir

```

#Tahmin

```{r}
test_x_x<-test_x%>%
  dplyr::select(-c("League","NewLeague","Division"))  # kategorik degiskenleri cikarttik

defaultSummary(data.frame(obs=test_y,  #gercek degerler trainingde
pred=as.vector(predict(lasso_cv_fit,as.matrix(test_x_x))))) # rmse hata kareler ortalamasının karekökü,mae mutlak hata ortalaması,r squared r kare degeri
```
#Model tuning

```{r}

ctrl<-trainControl(method="cv",number=10)
set.seed(100)

lasso_grid<-data.frame(
  fraction=seq(.05,1,length=20))


lasso_tune<-train(train_x_x,train_y,
                method="lasso",
                trControl=ctrl,
                tuneGrid=lasso_grid,
                preProc=c("center","scale"))

plot(lasso_tune)

lasso_tune$results %>% filter(fraction==as.numeric(lasso_tune$bestTune))

lasso_tune$bestTune
lasso_tune$finalModel

defaultSummary(data.frame(obs=test_y,  
pred=as.vector(predict(lasso_tune,as.matrix(test_x_x)))))

```























