---
title: "ridge_regresyon"
author: "ridge_regresyon"
date: "18 09 2021"
output: html_document
---

#Ridge regresyon

Mass,ta yer alan lm.ridge elasticnet'te yer alan enet yada glmnet

#Model

```{r}

train_x_x<-train_x %>% 
  dplyr::select(-c("League","NewLeague","Division"))  # kategorik degiskenleri cikarttik

ridge_fit<-glmnet(as.matrix(train_x_x),
                  y=train_y,
                  alpha=0
                  )
ridge_fit

summary(ridge_fit)

names(ridge_fit) # icinden erisilebilecek degerler

ridge_fit$beta

plot(ridge_fit,xvar="lambda",label=T)

min(log(ridge_fit$lambda))

```

#Dogru lambda icin cv'nin kullanilmasi

```{r}
ridge_cv_fit<-cv.glmnet(as.matrix(train_x_x),
                  y=train_y,
                  alpha=0
                  )

ridge_cv_fit$lambda
ridge_cv_fit
plot(ridge_cv_fit)

ridge_cv_fit$lambda.min
ridge_cv_fit$lambda.1se

coef(ridge_cv_fit,"lambda.min")

tidy(ridge_cv_fit)

```
#Tahmin

```{r}
test_x_x<-test_x%>%
  dplyr::select(-c("League","NewLeague","Division"))  # kategorik degiskenleri cikarttik

defaultSummary(data.frame(obs=test_y,  #gercek degerler trainingde
pred=as.vector(predict(ridge_cv_fit,as.matrix(test_x_x))))) # rmse hata kareler ortalamasının karekökü,mae mutlak hata ortalaması,r squared r kare degeri
```
#Model tuning

```{r}

ctrl<-trainControl(method="cv",number=10)
set.seed(100)

ridge_grid<-data.frame(
  lambda=seq(0,.1,length=15))



ridge_tune<-train(train_x_x,train_y,
                method="ridge",
                trControl=ctrl,
                tuneGrid=ridge_grid,
                prePoc=c("center","scale"))


ridge_tune$results %>%filter(lambda==as.numeric(ridge_tune$bestTune))
ridge_tune$bestTune

defaultSummary(data.frame(obs=test_y,  
pred=as.vector(predict(ridge_tune,as.matrix(test_x_x)))))








```








